const Book = require('../models/Book');

/**
 * Create a book inside the database
 * @param {*} req Gets the ISBN, author, title, and is_checked_out from the json POST request
 * @param {*} res returns 201 if created else 500 for errors
 */
exports.createBook = async (req, res) => {
    try {
        const { ISBN, author, title, is_checked_out, genre} = req.body;
        const newBook = new Book({ ISBN, author, title, is_checked_out, genre });
        await newBook.save();
        res.status(201).json(newBook);
    } catch (error) {
        console.error('Error creating book:', error.message);
        res.status(500).json({ error: error.message });
    }
};

/**
 * Gets all the books from the database
 * @param {*} req The GET request
 * @param {*} res returns 200 if req is successful else 500
 */
exports.getAllBooks = async (req, res) => {
    try {
        const books = await Book.find();
        res.status(200).json(books);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

/**
 * Updates a book from the database using the _id tag that is autogenerated
 * @param {*} req The PUT request that contains the :id in params
 * @param {*} res returns 200 if successfully updated books else 500
 * @returns 
 */
exports.updateBook = async (req, res) => {
    try {
        const { id } = req.params;
        const updatedBook = await Book.findByIdAndUpdate(id, req.body, { new: true });
        if (!updatedBook) return res.status(404).json({ error: 'Book not found' });
        res.status(200).json(updatedBook);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

/**
 * Deletes a book from the database using the _id tag
 * @param {*} req The DELETE request that contains the :id in params
 * @param {*} res returns 200 if successfully deleted the book else 500
 * @returns 
 */
exports.deleteBook = async (req, res) => {
    try {
        const { id } = req.params;
        const deletedBook = await Book.findByIdAndDelete(id);
        if (!deletedBook) return res.status(404).json({ error: 'Book not found' });
        res.status(200).json({ message: `Book deleted successfully with id = ${id} and ISBN = ${deletedBook.ISBN} and title = ${deletedBook.title}` });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};
